language: node_js
#node_js:
#- "8"
before_script:
  - npm install -g gulp-cli
script: gulp build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
